# Generated by Django 4.2.7 on 2023-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_rename_userid_cart_user_remove_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
