# Generated by Django 4.2.7 on 2023-11-25 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0007_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartData',
        ),
    ]
