# Generated by Django 4.2.7 on 2023-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_rename_cart_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='productImage',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cartdata',
            name='productname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cartdata',
            name='productprice',
            field=models.CharField(default='', max_length=20),
        ),
    ]
