# Generated by Django 4.2.7 on 2023-11-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_rename_productimage_cartdata_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdata',
            name='productimage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
