# Generated by Django 4.2.7 on 2023-11-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_alter_cartdata_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdata',
            name='productimage',
        ),
        migrations.RemoveField(
            model_name='cartdata',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='cartdata',
            name='productprice',
        ),
    ]
