# Generated by Django 4.2.7 on 2023-11-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_remove_cartdata_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_shipping',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
