# Generated by Django 4.2.7 on 2023-11-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_product_product_discount_product_product_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_shipping',
            field=models.IntegerField(null=True),
        ),
    ]
