# Generated by Django 4.2.7 on 2023-11-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_alter_product_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_shipping',
        ),
    ]
