# Generated by Django 4.2.7 on 2023-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='paymentMode',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
