# Generated by Django 4.2.7 on 2023-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_billing_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='orederDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
