# Generated by Django 4.2.7 on 2023-12-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0019_billing_orederdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_discount',
        ),
    ]
