# Generated by Django 4.2.7 on 2023-12-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0020_remove_product_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shopapp.category'),
            preserve_default=False,
        ),
    ]
